export const CREATE_PROJECTS = 'CREATE_PROJECTS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const LOADING_PROJECTS = 'LOADING_PROJECTS';

