export const CREATE_PROJECTS = 'CREATE_PROJECTS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const LOADING_PROJECTS = 'LOADING_PROJECTS';

export const CREATE_MEDIA = 'CREATE_MEDIA';
export const GET_MEDIA = 'GET_MEDIA';
export const GET_SINGLE_MEDIA = 'GET_SINGLE_MEDIA';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const DELETE_MEDIA = 'DELETE_MEDIA';
export const LOADING_MEDIA = 'LOADING_MEDIA';
